import type { ThemeConfig, ThemeComponents, TypographyConfig } from '../types/portfolio';

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Returns a token value or falls back to a CSS variable / hardcoded default */
function t<K extends keyof ThemeComponents>(
  c: ThemeComponents | undefined,
  section: K,
  key: keyof NonNullable<ThemeComponents[K]>,
  fallback: string,
): string {
  const block = c?.[section] as Record<string, string | number | undefined> | undefined;
  const val = block?.[key as string];
  return val !== undefined ? String(val) : fallback;
}

// ─── Main export ─────────────────────────────────────────────────────────────

export function generateCSS(theme: ThemeConfig, typography: TypographyConfig): string {
  const c = theme.components;

  // ── Resolve component tokens with per-theme defaults ──────────────────────
  const btn = {
    radius:        t(c, 'button', 'radius',        '4px'),
    letterSpacing: t(c, 'button', 'letterSpacing',  '0.04em'),
    textTransform: t(c, 'button', 'textTransform',  'none'),
    padding:       t(c, 'button', 'padding',        '0.85rem 1.75rem'),
    fontSize:      t(c, 'button', 'fontSize',       '0.875rem'),
    fontWeight:    t(c, 'button', 'fontWeight',     '500'),
    shadow:        t(c, 'button', 'shadow',         'none'),
    variant:       t(c, 'button', 'variant',        'fill'),
  };

  const card = {
    radius:         t(c, 'card', 'radius',         '8px'),
    shadow:         t(c, 'card', 'shadow',         '0 2px 12px rgba(0,0,0,0.08)'),
    border:         t(c, 'card', 'border',         '1px solid var(--border)'),
    background:     t(c, 'card', 'background',     'var(--surface)'),
    hoverTransform: t(c, 'card', 'hoverTransform', 'translateY(-3px)'),
    hoverShadow:    t(c, 'card', 'hoverShadow',    '0 8px 32px rgba(0,0,0,0.12)'),
    padding:        t(c, 'card', 'padding',        '1.5rem'),
  };

  const tag = {
    radius:        t(c, 'tag', 'radius',        '4px'),
    padding:       t(c, 'tag', 'padding',       '0.25rem 0.6rem'),
    fontSize:      t(c, 'tag', 'fontSize',      '0.7rem'),
    letterSpacing: t(c, 'tag', 'letterSpacing', '0.04em'),
    textTransform: t(c, 'tag', 'textTransform', 'none'),
    border:        t(c, 'tag', 'border',        'none'),
    background:    t(c, 'tag', 'background',    'var(--accent-muted)'),
    color:         t(c, 'tag', 'color',         'var(--accent)'),
  };

  const heading = {
    letterSpacing: t(c, 'heading', 'letterSpacing', '-0.03em'),
    lineHeight:    t(c, 'heading', 'lineHeight',    '1.05'),
    textTransform: t(c, 'heading', 'textTransform', 'none'),
    fontStyle:     t(c, 'heading', 'fontStyle',     'normal'),
  };

  const divider = {
    style:     t(c, 'divider', 'style',     'solid'),
    opacity:   t(c, 'divider', 'opacity',   '0.2'),
    thickness: t(c, 'divider', 'thickness', '1px'),
  };

  const input = {
    radius:      t(c, 'input', 'radius',      '6px'),
    border:      t(c, 'input', 'border',      '1px solid var(--border)'),
    background:  t(c, 'input', 'background',  'var(--surface)'),
    focusBorder: t(c, 'input', 'focusBorder', '1px solid var(--accent)'),
    padding:     t(c, 'input', 'padding',     '0.75rem 1rem'),
  };

  const surf = {
    backdropFilter: t(c, 'surface', 'backdropFilter', 'blur(12px)'),
  };

  const img = {
    radius:         t(c, 'image', 'radius',         '0px'),
    objectFit:      t(c, 'image', 'objectFit',      'cover'),
    aspectRatio:    t(c, 'image', 'aspectRatio',    'auto'),
    border:         t(c, 'image', 'border',         'none'),
    shadow:         t(c, 'image', 'shadow',         'none'),
    filter:         t(c, 'image', 'filter',         'none'),
    hoverFilter:    t(c, 'image', 'hoverFilter',    'none'),
    hoverTransform: t(c, 'image', 'hoverTransform', 'scale(1.02)'),
    transition:     t(c, 'image', 'transition',     '0.4s ease'),
  };

  // ── Button primary variant CSS ─────────────────────────────────────────────
  const btnVariantCSS = buildButtonVariantCSS(btn.variant, theme);

  return `
/* ────────────────────────────────────────────────────────────────────────────
   Theme: ${theme.name}  (style: ${theme.style ?? 'default'})
   Generated by Portfolio Builder — do not edit manually.
──────────────────────────────────────────────────────────────────────────── */

*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

/* ── Design tokens ───────────────────────────────────────────────────────── */
:root {
  /* Color palette */
  --bg:           ${theme.colors.background};
  --surface:      ${theme.colors.surface};
  --text:         ${theme.colors.text};
  --text-muted:   ${theme.colors.textMuted};
  --accent:       ${theme.colors.accent};
  --accent-muted: ${theme.colors.accentMuted};
  --border:       ${theme.colors.border};

  /* Typography */
  --font-heading: '${typography.headingFont}', sans-serif;
  --font-body:    '${typography.bodyFont}', sans-serif;
  --base-size:    ${typography.baseSize}rem;
  --line-height:  ${typography.lineHeight};

  /* Typographic scale */
  --text-xs:   clamp(0.65rem, 1.5vw, 0.75rem);
  --text-sm:   clamp(0.8rem,  1.8vw, 0.875rem);
  --text-base: clamp(0.9rem,  2vw,   1rem);
  --text-lg:   clamp(1rem,    2.5vw, 1.25rem);
  --text-xl:   clamp(1.1rem,  3vw,   1.5rem);
  --text-2xl:  clamp(1.25rem, 4vw,   2rem);
  --text-3xl:  clamp(1.5rem,  5vw,   3rem);
  --text-4xl:  clamp(2rem,    6vw,   4.5rem);
  --text-5xl:  clamp(2.5rem,  8vw,   7rem);

  /* Component tokens — exposed as CSS variables so custom HTML can use them */
  --btn-radius:         ${btn.radius};
  --btn-letter-spacing: ${btn.letterSpacing};
  --btn-text-transform: ${btn.textTransform};
  --btn-padding:        ${btn.padding};
  --btn-font-size:      ${btn.fontSize};
  --btn-font-weight:    ${btn.fontWeight};
  --btn-shadow:         ${btn.shadow};

  --card-radius:          ${card.radius};
  --card-shadow:          ${card.shadow};
  --card-border:          ${card.border};
  --card-bg:              ${card.background};
  --card-hover-transform: ${card.hoverTransform};
  --card-hover-shadow:    ${card.hoverShadow};
  --card-padding:         ${card.padding};

  --tag-radius:          ${tag.radius};
  --tag-padding:         ${tag.padding};
  --tag-font-size:       ${tag.fontSize};
  --tag-letter-spacing:  ${tag.letterSpacing};
  --tag-text-transform:  ${tag.textTransform};
  --tag-border:          ${tag.border};
  --tag-bg:              ${tag.background};
  --tag-color:           ${tag.color};

  --heading-letter-spacing: ${heading.letterSpacing};
  --heading-line-height:    ${heading.lineHeight};
  --heading-text-transform: ${heading.textTransform};
  --heading-font-style:     ${heading.fontStyle};

  --divider-style:     ${divider.style};
  --divider-opacity:   ${divider.opacity};
  --divider-thickness: ${divider.thickness};

  --input-radius:       ${input.radius};
  --input-border:       ${input.border};
  --input-bg:           ${input.background};
  --input-focus-border: ${input.focusBorder};
  --input-padding:      ${input.padding};

  --surface-backdrop: ${surf.backdropFilter};

  /* Image tokens */
  --img-radius:          ${img.radius};
  --img-object-fit:      ${img.objectFit};
  --img-aspect-ratio:    ${img.aspectRatio};
  --img-border:          ${img.border};
  --img-shadow:          ${img.shadow};
  --img-filter:          ${img.filter};
  --img-hover-filter:    ${img.hoverFilter};
  --img-hover-transform: ${img.hoverTransform};
  --img-transition:      ${img.transition};
}

/* ── Base ────────────────────────────────────────────────────────────────── */
html {
  font-size: var(--base-size);
  scroll-behavior: auto;
}
body {
  background: var(--bg);
  color: var(--text);
  font-family: var(--font-body);
  line-height: var(--line-height);
  -webkit-font-smoothing: antialiased;
  overflow-x: hidden;
  cursor: default;
}

/* ── Headings ────────────────────────────────────────────────────────────── */
h1, h2, h3, h4, h5, h6 {
  font-family: var(--font-heading);
  font-weight: ${typography.headingWeight};
  line-height: var(--heading-line-height);
  letter-spacing: var(--heading-letter-spacing);
  text-transform: var(--heading-text-transform);
  font-style: var(--heading-font-style);
}

/* ── Links ───────────────────────────────────────────────────────────────── */
a {
  color: var(--accent);
  text-decoration: none;
  transition: opacity 0.2s ease;
}
a:hover { opacity: 0.75; }

/* ── Buttons ─────────────────────────────────────────────────────────────── */
.btn, button.btn, a.btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  padding: var(--btn-padding);
  font-family: var(--font-body);
  font-size: var(--btn-font-size);
  font-weight: var(--btn-font-weight);
  letter-spacing: var(--btn-letter-spacing);
  text-transform: var(--btn-text-transform);
  border-radius: var(--btn-radius);
  cursor: pointer;
  transition: all 0.22s cubic-bezier(0.4, 0, 0.2, 1);
  text-decoration: none;
  white-space: nowrap;
  position: relative;
  overflow: hidden;
}
${btnVariantCSS}

/* Primary (alias — sections use .btn-primary) */
.btn-primary {
  /* inherits from .btn + variant-specific rules above */
}

/* ── Cards ───────────────────────────────────────────────────────────────── */
.card {
  background: var(--card-bg);
  border: var(--card-border);
  border-radius: var(--card-radius);
  box-shadow: var(--card-shadow);
  padding: var(--card-padding);
  transition: transform 0.28s cubic-bezier(0.4, 0, 0.2, 1),
              box-shadow 0.28s cubic-bezier(0.4, 0, 0.2, 1);
  position: relative;
  overflow: hidden;
}
.card:hover {
  transform: var(--card-hover-transform);
  box-shadow: var(--card-hover-shadow);
}

/* Card variants */
.card-image {
  padding: 0;
}
.card-image .card-body {
  padding: var(--card-padding);
}
.card-image img, .card-image video {
  width: 100%;
  height: 100%;
  object-fit: cover;
  display: block;
  border-radius: var(--card-radius) var(--card-radius) 0 0;
}

.card-glass {
  background: rgba(${hexToRgb(theme.colors.surface)}, 0.5);
  backdrop-filter: var(--surface-backdrop);
  -webkit-backdrop-filter: var(--surface-backdrop);
}

/* ── Images / Media ─────────────────────────────────────────────────────── */

/* Wrapper — constrains image and provides hover context */
.img-wrapper {
  overflow: hidden;
  border-radius: var(--img-radius);
  border: var(--img-border);
  box-shadow: var(--img-shadow);
  display: block;
  position: relative;
}

/* The image itself inherits theme tokens */
.img-themed,
.img-wrapper img {
  display: block;
  width: 100%;
  height: 100%;
  object-fit: var(--img-object-fit);
  border-radius: var(--img-radius);
  border: var(--img-border);
  box-shadow: var(--img-shadow);
  filter: var(--img-filter);
  transition: filter var(--img-transition),
              transform var(--img-transition),
              box-shadow var(--img-transition);
}
.img-themed:hover,
.img-wrapper:hover img {
  filter: var(--img-hover-filter);
  transform: var(--img-hover-transform);
}

/* Portrait / square helpers */
.img-square  { aspect-ratio: 1 / 1; }
.img-wide    { aspect-ratio: 16 / 9; }
.img-portrait { aspect-ratio: 3 / 4; }
.img-cinematic { aspect-ratio: 21 / 9; }

/* ── Tags / Badges ───────────────────────────────────────────────────────── */
.tag, .badge {
  display: inline-flex;
  align-items: center;
  gap: 0.35rem;
  padding: var(--tag-padding);
  font-size: var(--tag-font-size);
  font-family: var(--font-body);
  letter-spacing: var(--tag-letter-spacing);
  text-transform: var(--tag-text-transform);
  border-radius: var(--tag-radius);
  border: var(--tag-border);
  background: var(--tag-bg);
  color: var(--tag-color);
  font-weight: 500;
  white-space: nowrap;
  line-height: 1;
  transition: opacity 0.15s;
}
.tag:hover { opacity: 0.8; }

/* ── Dividers ────────────────────────────────────────────────────────────── */
hr, .divider {
  border: none;
  border-top: var(--divider-thickness) var(--divider-style) var(--border);
  opacity: var(--divider-opacity);
  width: 100%;
  margin: 0;
}

/* ── Form inputs ─────────────────────────────────────────────────────────── */
input[type="text"],
input[type="email"],
input[type="tel"],
input[type="url"],
textarea,
select,
.input {
  width: 100%;
  padding: var(--input-padding);
  font-family: var(--font-body);
  font-size: var(--text-base);
  color: var(--text);
  background: var(--input-bg);
  border: var(--input-border);
  border-radius: var(--input-radius);
  outline: none;
  transition: border 0.2s ease, box-shadow 0.2s ease;
  appearance: none;
}
input[type="text"]:focus,
input[type="email"]:focus,
input[type="tel"]:focus,
input[type="url"]:focus,
textarea:focus,
select:focus,
.input:focus {
  border: var(--input-focus-border);
  box-shadow: 0 0 0 3px ${hexToRgbAlpha(theme.colors.accent, 0.15)};
}
textarea { resize: vertical; min-height: 120px; }
::placeholder { color: var(--text-muted); opacity: 0.7; }

/* ── Section defaults ────────────────────────────────────────────────────── */
.section {
  position: relative;
  width: 100%;
}

/* ── Utility classes ─────────────────────────────────────────────────────── */
.text-accent  { color: var(--accent); }
.text-muted   { color: var(--text-muted); }
.text-surface { color: var(--surface); }

.bg-surface   { background: var(--surface); }
.bg-accent    { background: var(--accent); }

.border-default { border: var(--card-border); }

/* ── Animations ──────────────────────────────────────────────────────────── */
@property --clip-progress {
  syntax: '<percentage>';
  initial-value: 100%;
  inherits: false;
}
[data-reveal] {
  clip-path: inset(var(--clip-progress) 0% 0% 0%);
}
@keyframes bounce {
  0%, 100% { transform: translateY(0); }
  50%       { transform: translateY(10px); }
}
@keyframes fadeUp {
  from { opacity: 0; transform: translateY(24px); }
  to   { opacity: 1; transform: translateY(0); }
}
@keyframes scaleIn {
  from { opacity: 0; transform: scale(0.95); }
  to   { opacity: 1; transform: scale(1); }
}
@keyframes shimmer {
  0%   { background-position: -200% center; }
  100% { background-position: 200% center; }
}

/* ── Lenis ───────────────────────────────────────────────────────────────── */
html.lenis { height: auto; }
.lenis.lenis-smooth { scroll-behavior: auto; }
.lenis.lenis-smooth [data-lenis-prevent] { overscroll-behavior: contain; }

/* ── Scrollbars ──────────────────────────────────────────────────────────── */
html, body, * {
  scrollbar-width: thin;
  scrollbar-color: ${hexToRgbAlpha(theme.colors.accent, 0.15)} transparent;
}
::-webkit-scrollbar { width: 4px; height: 4px; }
::-webkit-scrollbar-track { background: transparent; }
::-webkit-scrollbar-thumb {
  background: ${hexToRgbAlpha(theme.colors.accent, 0.18)};
  border-radius: 999px;
  transition: background 0.2s;
}
::-webkit-scrollbar-thumb:hover {
  background: ${hexToRgbAlpha(theme.colors.accent, 0.35)};
}
::-webkit-scrollbar-corner { background: transparent; }

/* ── Accessibility ───────────────────────────────────────────────────────── */
:focus-visible { outline: 2px solid var(--accent); outline-offset: 3px; }
#portfolio { container-type: inline-size; }
@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    animation-duration: 0.01ms !important;
    transition-duration: 0.01ms !important;
  }
}

/* ══════════════════════════════════════════════════════════════════
   RESPONSIVE BREAKPOINTS
   Using container queries (cqw) on #portfolio so preview-frame
   width changes trigger layout shifts — not the browser viewport.
══════════════════════════════════════════════════════════════════ */

/* ── Tablet (≤ 768px container width) ────────────────────────────── */
@container (max-width: 768px) {
  /* Typography scale tightening */
  :root {
    --text-4xl: clamp(1.75rem, 7cqi, 3.5rem);
    --text-5xl: clamp(2rem,    9cqi, 5rem);
  }

  /* Hero: all layouts stack to single column */
  .section-hero {
    padding: 6vw 6vw !important;
    min-height: 90vh !important;
  }
  .section-hero [style*="grid-template-columns:1fr 1fr"],
  .section-hero [style*="grid-template-columns: 1fr 1fr"] {
    grid-template-columns: 1fr !important;
  }
  /* Bento collapses from 4 cols → 2 cols */
  .section-hero [style*="grid-template-columns:repeat(4,1fr)"],
  .section-hero [style*="grid-template-columns: repeat(4, 1fr)"] {
    grid-template-columns: repeat(2, 1fr) !important;
    grid-template-rows: auto !important;
  }

  /* About: 2-col → 1-col */
  .section-about {
    padding: 6vw !important;
  }
  .section-about [style*="grid-template-columns:1fr 1fr"],
  .section-about [style*="grid-template-columns: 1fr 1fr"],
  .section-about [style*="grid-template-columns:1fr 2fr"],
  .section-about [style*="grid-template-columns: 1fr 2fr"] {
    grid-template-columns: 1fr !important;
    gap: 3rem !important;
  }
  /* Stats grid: 3 cols → 2 cols */
  .section-about [style*="grid-template-columns:repeat(3,1fr)"],
  .section-about [style*="grid-template-columns: repeat(3, 1fr)"] {
    grid-template-columns: repeat(2, 1fr) !important;
  }

  /* Work: feature items → single column */
  .section-work {
    padding: 6vw !important;
  }
  .section-work [style*="grid-template-columns:1fr 1fr"],
  .section-work [style*="grid-template-columns: 1fr 1fr"] {
    grid-template-columns: 1fr !important;
    direction: ltr !important;
    gap: 2rem !important;
  }
  /* Work bento: 3-col → 2-col */
  .section-work [style*="grid-template-columns:repeat(3,1fr)"],
  .section-work [style*="grid-template-columns: repeat(3, 1fr)"] {
    grid-template-columns: repeat(2, 1fr) !important;
  }

  /* Contact: split → single column */
  .section-contact {
    padding: 6vw !important;
  }
  .section-contact [style*="grid-template-columns:1fr 1fr"],
  .section-contact [style*="grid-template-columns: 1fr 1fr"] {
    grid-template-columns: 1fr !important;
    gap: 3rem !important;
  }
  /* Contact email font */
  .section-contact a[style*="font-size:var(--text-4xl)"] {
    font-size: var(--text-3xl) !important;
  }

  /* Skills / Process: retain readable width */
  .section-skills,
  .section-process {
    padding: 6vw !important;
  }
  .section-skills [style*="grid-template-columns:repeat(3,1fr)"],
  .section-skills [style*="grid-template-columns: repeat(3, 1fr)"] {
    grid-template-columns: repeat(2, 1fr) !important;
  }
  .section-process [style*="grid-template-columns:5rem 1fr"],
  .section-process [style*="grid-template-columns: 5rem 1fr"] {
    grid-template-columns: 3.5rem 1fr !important;
    gap: 1.25rem !important;
  }
}

/* ── Mobile (≤ 480px container width) ────────────────────────────── */
@container (max-width: 480px) {
  :root {
    --text-3xl: clamp(1.25rem, 6cqi, 2rem);
    --text-4xl: clamp(1.5rem,  8cqi, 2.5rem);
    --text-5xl: clamp(1.75rem, 10cqi, 3.5rem);
  }

  /* Hero */
  .section-hero {
    padding: 5vw 5vw !important;
    min-height: 85vh !important;
    align-items: flex-start !important;
    padding-top: 15vw !important;
  }
  /* Bento collapses to single column */
  .section-hero [style*="grid-template-columns:repeat(2,1fr)"],
  .section-hero [style*="grid-template-columns: repeat(2, 1fr)"] {
    grid-template-columns: 1fr !important;
  }
  /* Bento grid spans reset */
  .section-hero [style*="grid-column:1/3"],
  .section-hero [style*="grid-column: 1/3"] {
    grid-column: auto !important;
    grid-row: auto !important;
  }

  /* About */
  .section-about {
    padding: 5vw !important;
  }
  /* Center layout photo shrinks */
  .section-about [style*="width:180px;height:180px"] {
    width: 120px !important;
    height: 120px !important;
  }
  /* Stats: 2 cols on mobile */
  .section-about [style*="grid-template-columns:repeat(3,1fr)"],
  .section-about [style*="grid-template-columns: repeat(3, 1fr)"],
  .section-about [style*="grid-template-columns:repeat(2,1fr)"],
  .section-about [style*="grid-template-columns: repeat(2, 1fr)"] {
    grid-template-columns: repeat(2, 1fr) !important;
  }

  /* Work */
  .section-work {
    padding: 5vw !important;
  }
  /* Work bento: full single column */
  .section-work [style*="grid-template-columns:repeat(2,1fr)"],
  .section-work [style*="grid-template-columns: repeat(2, 1fr)"] {
    grid-template-columns: 1fr !important;
  }
  .section-work [style*="grid-column:1/3"],
  .section-work [style*="grid-column: 1/3"] {
    grid-column: auto !important;
  }

  /* Skills / Process */
  .section-skills,
  .section-process {
    padding: 5vw !important;
  }
  .section-skills [style*="grid-template-columns:repeat(2,1fr)"],
  .section-skills [style*="grid-template-columns: repeat(2, 1fr)"] {
    grid-template-columns: 1fr !important;
  }
  .section-skills [style*="grid-column:1/3"],
  .section-skills [style*="grid-column: 1/3"] {
    grid-column: auto !important;
  }
  .section-process [style*="grid-template-columns:3.5rem 1fr"],
  .section-process [style*="grid-template-columns: 3.5rem 1fr"],
  .section-process [style*="grid-template-columns:5rem 1fr"],
  .section-process [style*="grid-template-columns: 5rem 1fr"],
  .section-process [style*="grid-template-columns:3rem 1fr"],
  .section-process [style*="grid-template-columns: 3rem 1fr"] {
    grid-template-columns: 2.5rem 1fr !important;
    gap: 1rem !important;
  }

  /* Contact */
  .section-contact {
    padding: 5vw !important;
    min-height: auto !important;
  }
  .section-contact a[href^="mailto"] {
    font-size: var(--text-2xl) !important;
    word-break: break-all !important;
  }

  /* Work list layout: compact */
  .section-work a[style*="grid-template-columns:4rem 1fr auto"],
  .section-work a[style*="grid-template-columns: 4rem 1fr auto"] {
    grid-template-columns: 2.5rem 1fr auto !important;
    gap: 1rem !important;
  }

  /* Process cards: auto-fit already handles it */
  .section-process [style*="display:grid"] {
    grid-template-columns: 1fr !important;
  }
}
`;
}

// ─── Button variant CSS ───────────────────────────────────────────────────────


function buildButtonVariantCSS(
  variant: string,
  theme: ThemeConfig,
): string {
  const accentRgb = hexToRgb(theme.colors.accent);
  const shadow = theme.components?.button?.shadow ?? 'none';

  switch (variant) {
    case 'fill':
      return `
.btn, .btn-primary {
  background: var(--accent);
  color: ${theme.darkMode ? '#000' : '#fff'};
  border: 2px solid var(--accent);
}
.btn:hover, .btn-primary:hover {
  opacity: 0.88;
  box-shadow: var(--btn-shadow);
  transform: translateY(-1px);
}
.btn:active { transform: translateY(0); opacity: 1; }`;

    case 'outline':
      return `
.btn, .btn-primary {
  background: transparent;
  color: var(--accent);
  border: 1.5px solid var(--accent);
}
.btn:hover, .btn-primary:hover {
  background: var(--accent);
  color: ${theme.darkMode ? '#000' : '#fff'};
  box-shadow: var(--btn-shadow);
  transform: translateY(-1px);
}
.btn:active { transform: translateY(0); }`;

    case 'ghost':
      return `
.btn, .btn-primary {
  background: transparent;
  color: var(--text);
  border: 1px solid var(--border);
}
.btn:hover, .btn-primary:hover {
  background: var(--surface);
  border-color: var(--text-muted);
  transform: translateY(-1px);
}
.btn:active { transform: translateY(0); }`;

    case 'pill':
      return `
.btn, .btn-primary {
  background: var(--accent);
  color: ${theme.darkMode ? '#000' : '#fff'};
  border: none;
  border-radius: 999px;
}
.btn:hover, .btn-primary:hover {
  opacity: 0.88;
  box-shadow: ${shadow};
  transform: translateY(-2px) scale(1.02);
}
.btn:active { transform: translateY(0) scale(1); }`;

    default:
      return `
.btn, .btn-primary {
  background: var(--accent);
  color: ${theme.darkMode ? '#000' : '#fff'};
  border: 2px solid var(--accent);
}
.btn:hover, .btn-primary:hover {
  opacity: 0.85;
  box-shadow: var(--btn-shadow);
}`;
  }
}

// ─── Colour helpers ───────────────────────────────────────────────────────────

/** Convert 3 or 6-digit hex → "r, g, b" string */
function hexToRgb(hex: string): string {
  const clean = hex.replace('#', '');
  const full = clean.length === 3
    ? clean.split('').map(c => c + c).join('')
    : clean;
  const r = parseInt(full.slice(0, 2), 16);
  const g = parseInt(full.slice(2, 4), 16);
  const b = parseInt(full.slice(4, 6), 16);
  if (isNaN(r) || isNaN(g) || isNaN(b)) return '128, 128, 128';
  return `${r}, ${g}, ${b}`;
}

/** Convert hex + alpha → rgba() string */
function hexToRgbAlpha(hex: string, alpha: number): string {
  return `rgba(${hexToRgb(hex)}, ${alpha})`;
}
